#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.6.2
# Product:       sfa4x
# Model-Version: 2.1.0
#

import pytest
from sensirion_i2c_sfa4x.device import Sfa4xDevice


@pytest.fixture
def sensor(channel_provider):
    channel_provider.i2c_frequency = 100e3
    channel_provider.supply_voltage = 3.3
    with channel_provider:
        channel = channel_provider.get_channel(slave_address=0x5D,
                                               crc_parameters=(8, 0x31, 0xff, 0x0))
        yield Sfa4xDevice(channel)


def test_get_serial_number1(sensor):
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )


def test_get_product_id1(sensor):
    product_id = sensor.get_product_id()
    print(f"product_id: {product_id}; "
          )


def test_stop_continuous_measurement1(sensor):
    sensor.stop_continuous_measurement()


def test_start_continuous_measurement1(sensor):
    sensor.start_continuous_measurement()
    (hcho_concentration, relative_humidity, temperature, status
     ) = sensor.read_measurement_data_raw()
    print(f"hcho_concentration: {hcho_concentration}; "
          f"relative_humidity: {relative_humidity}; "
          f"temperature: {temperature}; "
          f"status: {status}; "
          )
    (hcho_concentration, relative_humidity, temperature, status
     ) = sensor.read_measurement_data()
    print(f"hcho_concentration: {hcho_concentration}; "
          f"relative_humidity: {relative_humidity}; "
          f"temperature: {temperature}; "
          f"status: {status}; "
          )
    sensor.stop_continuous_measurement()

