#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.6.2
# Product:       sfa4x
# Model-Version: 2.1.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sfa4x.device import Sfa4xDevice

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x5D,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sfa4xDevice(channel)
    sensor.stop_continuous_measurement()
    product_id = sensor.get_product_id()
    print(f"product_id: {product_id}; "
          )
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )
    sensor.start_continuous_measurement()
    for i in range(50):
        try:
            time.sleep(1.0)
            (hcho_concentration, relative_humidity, temperature, status
             ) = sensor.read_measurement_data()
            print(f"hcho_concentration: {hcho_concentration}; "
                  f"relative_humidity: {relative_humidity}; "
                  f"temperature: {temperature}; "
                  f"status: {status}; "
                  )
        except BaseException:
            continue
    sensor.stop_continuous_measurement()
